version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: lingo_db    
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lingo_mentor
  backend:
    build: 
      context: ./backend/
    container_name: lingo_backend  
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lingo_mentor
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTOR=update
  frontend:
    build:
      context: ./frontend/
    container_name: lingo_frontend
    depends_on:
      - backend
    ports:
      - 5173:5173
