@startuml useCase

!theme blueprint

actor User as u
usecase (Выбрать сущность) as ce
usecase (Создать новую запись) as cn
usecase (Удалить запись) as di
usecase (Редактировать запись) as ei
usecase (Просмотр \n данных \n сущности) as vd
usecase (Выбор записи) as choose_item
u - ce
ce .right.> vd: <<include>>
vd .down.> cn: <<extend>>

vd <.right. choose_item : <<extend>>
choose_item <.right. di : <<extend>>
choose_item <.down. ei : <<exntend>>

(Просмотр \n преподавателей) .down.> vd : <<extend>>
(Просмотр \n занятий) .down.> vd : <<extend>>
(Просмотр \n языков) .down.> vd : <<extend>>
(Просмотр \n типов занятий) .down.> vd : <<extend>>


(Создать преподавателя) .right.> cn : <<extend>>
(Создать занятие) .up.> cn : <<extend>>
(Создать язык) .up.> cn : <<extend>>
(Создать тип занятия) .up.> cn : <<extend>>

(Удалить \n преподавателя) .down.> di : <<extend>>
(Удалить занятие) .down.> di : <<extend>>
(Удалить язык) .down.> di : <<extend>>
(Удалить тип занятия) .left.> di : <<extend>>

(Редактировать \n преподавателя) .up.> ei : <<extend>>
(Редактировать \n занятие) .left.> ei : <<extend>>
(Редактировать \n язык) .up.> ei : <<extend>>
(Редактировать \n тип занятия) .right.> ei : <<extend>>

@enduml